# The Use of K-Fold Cross Validation Using Sklearn Iris Data

### Importing Libraries

In [14]:
import numpy as np
import pandas as pd

### Importing Needed Algorithms

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [2]:
import warnings
warnings.filterwarnings('ignore')

### Loading Iris Data

In [16]:
from sklearn.datasets import load_iris

In [17]:
iris = load_iris()

In [18]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

### Importing K Fold Cross Validation

In [5]:
from sklearn.model_selection import cross_val_score

In [6]:
LR_scores = cross_val_score(LogisticRegression(), iris.data, iris.target)
LR_scores

array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [7]:
SVC_scores = cross_val_score(SVC(), iris.data, iris.target)
SVC_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [8]:
DTC_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target)
DTC_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [9]:
RFC_scores = cross_val_score(RandomForestClassifier(), iris.data, iris.target)
RFC_scores

array([0.96666667, 0.96666667, 0.93333333, 0.96666667, 1.        ])

### Calculating the average of each Algorithm

In [10]:
np.average(LR_scores)

0.9733333333333334

In [11]:
np.average(SVC_scores)

0.9666666666666666

In [12]:
np.average(DTC_scores)

0.9600000000000002

In [13]:
np.average(RFC_scores)

0.9666666666666668

## Logistic Regression Has The Best Score!