In [1]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [5]:
df = pd.read_csv('homeprices.csv')
df

,area,price
0,2600,550000
1,3000,565000
2,3200,610000
3,3600,680000
4,4000,725000


In [7]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression()

In [8]:
model.coef_

array([135.78767123])

In [9]:
model.intercept_

180616.43835616432

In [11]:
model.predict([[5000]])

C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [12]:
import pickle

In [13]:
with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [20]:
with open('model_pickle', 'rb') as f:
    mp= pickle.load(f)

In [21]:
mp.predict([[5000]])

C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

In [22]:
mp.coef_

array([135.78767123])

In [23]:
mp.intercept_

180616.43835616432

In [29]:
from sklearn.externals import joblib

ImportError: cannot import name 'joblib' from 'sklearn.externals' (C:\Users\CHUFESS\anaconda3\lib\site-packages\sklearn\externals\__init__.py)